import { Icon } from "@iconify/react";

// Iconify icon map with colored logos - exported for autocomplete component
export const iconMap: Record<string, string> = {
  // Programming Languages
  JavaScript: "logos:javascript",
  TypeScript: "logos:typescript-icon",
  Python: "logos:python",
  Java: "logos:java",
  PHP: "logos:php",
  Go: "logos:go",
  Rust: "logos:rust",
  C: "logos:c",
  "C++": "logos:c-plusplus",
  "C#": "logos:c-sharp",
  Ruby: "logos:ruby",
  Swift: "logos:swift",
  Kotlin: "logos:kotlin-icon",
  Dart: "logos:dart",
  Scala: "logos:scala",
  R: "logos:r-lang",
  Perl: "logos:perl",
  Lua: "logos:lua",
  Haskell: "logos:haskell-icon",
  Elixir: "logos:elixir",
  Clojure: "logos:clojure",
  "F#": "logos:fsharp",
  Julia: "logos:julia",
  MATLAB: "simple-icons:mathworks",
  Assembly: "simple-icons:assemblyscript",
  Solidity: "logos:solidity",
  SQL: "vscode-icons:file-type-sql",
  HTML: "logos:html-5",
  HTML5: "logos:html-5",
  CSS: "logos:css-3",
  CSS3: "logos:css-3",
  Markdown: "logos:markdown",
  JSON: "logos:json",
  YAML: "vscode-icons:file-type-yaml",
  XML: "vscode-icons:file-type-xml",

  // Frontend Frameworks
  React: "logos:react",
  "Next.js": "logos:nextjs-icon",
  Vue: "logos:vue",
  "Vue.js": "logos:vue",
  Angular: "logos:angular-icon",
  Svelte: "logos:svelte-icon",
  SvelteKit: "logos:svelte-icon",
  Nuxt: "logos:nuxt-icon",
  "Nuxt.js": "logos:nuxt-icon",
  Gatsby: "logos:gatsby",
  Remix: "logos:remix-icon",
  Astro: "logos:astro-icon",
  Qwik: "logos:qwik-icon",
  SolidJS: "logos:solidjs-icon",
  Preact: "logos:preact",
  Lit: "logos:lit-icon",
  Alpine: "logos:alpinejs-icon",
  "Alpine.js": "logos:alpinejs-icon",
  Ember: "logos:ember-tomster",
  "Ember.js": "logos:ember-tomster",
  Backbone: "logos:backbone-icon",
  jQuery: "logos:jquery",
  HTMX: "simple-icons:htmx",

  // Backend Frameworks
  "Node.js": "logos:nodejs-icon",
  Express: "skill-icons:expressjs-dark",
  "Express.js": "skill-icons:expressjs-dark",
  Django: "logos:django-icon",
  Flask: "logos:flask",
  Laravel: "logos:laravel",
  Spring: "logos:spring-icon",
  "Spring Boot": "logos:spring-icon",
  NestJS: "logos:nestjs",
  FastAPI: "logos:fastapi-icon",
  Rails: "logos:rails",
  "Ruby on Rails": "logos:rails",
  Koa: "logos:koa",
  Hono: "logos:hono",
  Deno: "logos:deno",
  Bun: "logos:bun",
  Fiber: "simple-icons:fiber",
  Gin: "simple-icons:gin",
  Echo: "simple-icons:go",
  Phoenix: "logos:phoenix",
  ASP: "logos:dotnet",
  ".NET": "logos:dotnet",
  "ASP.NET": "logos:dotnet",

  // Databases
  PostgreSQL: "logos:postgresql",
  MySQL: "logos:mysql-icon",
  MongoDB: "logos:mongodb-icon",
  Redis: "logos:redis",
  SQLite: "logos:sqlite",
  MariaDB: "logos:mariadb-icon",
  Firebase: "logos:firebase",
  Supabase: "logos:supabase-icon",
  Prisma: "logos:prisma",
  GraphQL: "logos:graphql",
  Cassandra: "logos:cassandra",
  ElasticSearch: "logos:elasticsearch",
  DynamoDB: "logos:aws-dynamodb",
  CouchDB: "logos:couchdb-icon",
  Neo4j: "logos:neo4j",
  Oracle: "logos:oracle",
  "SQL Server": "simple-icons:microsoftsqlserver",
  "Microsoft SQL Server": "simple-icons:microsoftsqlserver",
  Drizzle: "simple-icons:drizzle",
  Mongoose: "simple-icons:mongoose",
  Sequelize: "logos:sequelize",
  TypeORM: "simple-icons:typeorm",
  Hasura: "logos:hasura-icon",
  PlanetScale: "simple-icons:planetscale",
  Neon: "simple-icons:neon",
  Turso: "simple-icons:turso",
  Appwrite: "logos:appwrite-icon",
  Pocketbase: "simple-icons:pocketbase",

  // Cloud & DevOps
  Docker: "logos:docker-icon",
  Kubernetes: "logos:kubernetes",
  AWS: "logos:aws",
  "Amazon Web Services": "logos:aws",
  Azure: "logos:azure-icon",
  "Microsoft Azure": "logos:azure-icon",
  GCP: "logos:google-cloud",
  "Google Cloud": "logos:google-cloud",
  "Google Cloud Platform": "logos:google-cloud",
  Vercel: "logos:vercel-icon",
  Netlify: "logos:netlify-icon",
  Heroku: "logos:heroku-icon",
  DigitalOcean: "logos:digital-ocean",
  Linode: "logos:linode",
  Vultr: "simple-icons:vultr",
  Railway: "simple-icons:railway",
  Render: "simple-icons:render",
  Fly: "simple-icons:flydotio",
  "Fly.io": "simple-icons:flydotio",
  Jenkins: "logos:jenkins",
  "GitLab CI": "logos:gitlab",
  "GitHub Actions": "logos:github-actions",
  CircleCI: "logos:circleci",
  TravisCI: "logos:travis-ci",
  Terraform: "logos:terraform-icon",
  Ansible: "logos:ansible",
  Vagrant: "logos:vagrant-icon",
  Pulumi: "logos:pulumi-icon",
  ArgoCD: "logos:argo-icon",
  Helm: "logos:helm",

  // Version Control
  Git: "logos:git-icon",
  GitHub: "logos:github-icon",
  GitLab: "logos:gitlab",
  Bitbucket: "logos:bitbucket",
  Gitea: "logos:gitea",
  SourceTree: "logos:sourcetree",

  // IDEs & Editors
  "VS Code": "logos:visual-studio-code",
  "Visual Studio Code": "logos:visual-studio-code",
  "Visual Studio": "logos:visual-studio",
  "IntelliJ IDEA": "logos:intellij-idea",
  IntelliJ: "logos:intellij-idea",
  PyCharm: "logos:pycharm",
  WebStorm: "logos:webstorm",
  PhpStorm: "logos:phpstorm",
  GoLand: "logos:goland",
  Rider: "logos:rider",
  CLion: "logos:clion",
  DataGrip: "logos:datagrip",
  RubyMine: "logos:rubymine",
  "Android Studio": "logos:android-studio-icon",
  Xcode: "logos:xcode",
  "Sublime Text": "logos:sublime-text-icon",
  Atom: "logos:atom-icon",
  Vim: "logos:vim",
  Neovim: "logos:neovim",
  Emacs: "logos:gnu-emacs",
  Notepad: "vscode-icons:file-type-text",
  "Notepad++": "simple-icons:notepadplusplus",
  Eclipse: "logos:eclipse-icon",
  NetBeans: "logos:netbeans",
  Cursor: "simple-icons:cursor",
  Zed: "simple-icons:zedindustries",
  Windsurf: "simple-icons:codeium",
  Replit: "logos:replit-icon",
  CodeSandbox: "logos:codesandbox-icon",
  StackBlitz: "logos:stackblitz-icon",
  Codepen: "logos:codepen-icon",
  "GitHub Codespaces": "logos:github-codespaces",

  // Design Tools
  Figma: "logos:figma",
  Photoshop: "logos:adobe-photoshop",
  "Adobe Photoshop": "logos:adobe-photoshop",
  Illustrator: "logos:adobe-illustrator",
  "Adobe Illustrator": "logos:adobe-illustrator",
  XD: "logos:adobe-xd",
  "Adobe XD": "logos:adobe-xd",
  Sketch: "logos:sketch",
  Canva: "devicon:canva",
  InVision: "logos:invision-icon",
  "After Effects": "logos:adobe-after-effects",
  "Adobe After Effects": "logos:adobe-after-effects",
  "Premiere Pro": "logos:adobe-premiere",
  "Adobe Premiere": "logos:adobe-premiere",
  "Adobe Premiere Pro": "logos:adobe-premiere",
  Lightroom: "logos:adobe-lightroom",
  "Adobe Lightroom": "logos:adobe-lightroom",
  InDesign: "logos:adobe-indesign",
  "Adobe InDesign": "logos:adobe-indesign",
  Animate: "logos:adobe-animate",
  "Adobe Animate": "logos:adobe-animate",
  Audition: "logos:adobe-audition",
  "Adobe Audition": "logos:adobe-audition",
  Blender: "logos:blender",
  Cinema4D: "simple-icons:cinema4d",
  "Cinema 4D": "simple-icons:cinema4d",
  Maya: "simple-icons:autodeskmaya",
  "3ds Max": "simple-icons:autodesk",
  Unity: "logos:unity",
  "Unreal Engine": "logos:unrealengine-icon",
  Godot: "logos:godot-icon",
  CapCut: "simple-icons:capcut",
  DaVinci: "simple-icons:davinciresolve",
  "DaVinci Resolve": "simple-icons:davinciresolve",
  "Final Cut Pro": "simple-icons:apple",
  Framer: "logos:framer",
  Penpot: "simple-icons:penpot",
  Lunacy: "simple-icons:lunacy",
  Miro: "logos:miro-icon",
  Whimsical: "simple-icons:whimsical",
  Zeplin: "logos:zeplin",
  Principle: "simple-icons:principle",
  ProtoPie: "simple-icons:protopie",
  Origami: "simple-icons:origamistudio",
  Procreate: "simple-icons:procreate",
  Krita: "simple-icons:krita",
  GIMP: "simple-icons:gimp",
  Inkscape: "simple-icons:inkscape",
  CorelDRAW: "simple-icons:coreldraw",
  Affinity: "simple-icons:affinity",
  "Affinity Designer": "simple-icons:affinitydesigner",
  "Affinity Photo": "simple-icons:affinityphoto",

  // CSS Frameworks & Preprocessors
  "Tailwind CSS": "logos:tailwindcss-icon",
  TailwindCSS: "logos:tailwindcss-icon",
  Tailwind: "logos:tailwindcss-icon",
  Bootstrap: "logos:bootstrap",
  "Material-UI": "logos:material-ui",
  MUI: "logos:material-ui",
  "Chakra UI": "simple-icons:chakraui",
  "Ant Design": "logos:ant-design",
  Sass: "logos:sass",
  SCSS: "logos:sass",
  Less: "logos:less",
  PostCSS: "logos:postcss",
  Stylus: "logos:stylus",
  "Styled Components": "simple-icons:styledcomponents",
  Emotion: "simple-icons:emotion",
  "CSS Modules": "vscode-icons:file-type-css",
  UnoCSS: "logos:unocss",
  WindiCSS: "logos:windi-css",
  Bulma: "logos:bulma",
  Foundation: "logos:foundation",
  Semantic: "logos:semantic-ui",
  "Semantic UI": "logos:semantic-ui",
  PrimeReact: "simple-icons:primereact",
  PrimeVue: "simple-icons:primevue",
  Vuetify: "logos:vuetifyjs",
  Quasar: "logos:quasar",
  Radix: "simple-icons:radixui",
  "Radix UI": "simple-icons:radixui",
  "Headless UI": "simple-icons:headlessui",
  DaisyUI: "simple-icons:daisyui",
  shadcn: "simple-icons:shadcnui",
  "shadcn/ui": "simple-icons:shadcnui",

  // Testing
  Jest: "logos:jest",
  Cypress: "logos:cypress-icon",
  Playwright: "logos:playwright",
  Selenium: "logos:selenium",
  Postman: "logos:postman-icon",
  Insomnia: "logos:insomnia",
  Vitest: "logos:vitest",
  Mocha: "logos:mocha",
  Jasmine: "logos:jasmine",
  Karma: "logos:karma",
  Chai: "logos:chai",
  TestingLibrary: "logos:testing-library",
  "Testing Library": "logos:testing-library",
  Puppeteer: "logos:puppeteer",
  K6: "logos:k6",
  Gatling: "simple-icons:gatling",
  JMeter: "simple-icons:apachejmeter",

  // Package Managers
  npm: "logos:npm-icon",
  Yarn: "logos:yarn",
  pnpm: "logos:pnpm",
  pip: "logos:pypi",
  PyPI: "logos:pypi",
  Composer: "logos:composer",
  Cargo: "simple-icons:rust",
  NuGet: "logos:nuget-icon",
  Maven: "logos:maven",
  Gradle: "logos:gradle",
  CocoaPods: "logos:cocoapods",
  Homebrew: "logos:homebrew",

  // Build Tools
  Webpack: "logos:webpack",
  Vite: "logos:vitejs",
  Rollup: "logos:rollup",
  Parcel: "logos:parcel-icon",
  ESLint: "logos:eslint",
  Prettier: "logos:prettier",
  Babel: "logos:babel",
  esbuild: "logos:esbuild",
  SWC: "logos:swc",
  Turbopack: "logos:turbopack-icon",
  Turborepo: "logos:turborepo-icon",
  Nx: "logos:nx",
  Lerna: "logos:lerna",
  Grunt: "logos:grunt",
  Gulp: "logos:gulp",
  Make: "simple-icons:cmake",
  CMake: "simple-icons:cmake",
  Bazel: "logos:bazel-icon",

  // State Management & Libraries
  Redux: "logos:redux",
  Zustand: "simple-icons:zustand",
  MobX: "logos:mobx",
  Recoil: "logos:recoil-icon",
  Jotai: "simple-icons:jotai",
  XState: "simple-icons:xstate",
  Pinia: "logos:pinia",
  VueX: "logos:vue",
  TanStack: "simple-icons:reactquery",
  "React Query": "simple-icons:reactquery",
  SWR: "logos:swr",
  Apollo: "logos:apollostack",
  "Apollo Client": "logos:apollostack",
  Relay: "simple-icons:relay",
  Storybook: "logos:storybook-icon",
  "Three.js": "logos:threejs",
  "D3.js": "logos:d3",
  D3: "logos:d3",
  "Chart.js": "simple-icons:chartdotjs",
  Recharts: "simple-icons:chartdotjs",
  "Framer Motion": "logos:framer",
  GSAP: "simple-icons:greensock",
  Lottie: "simple-icons:lottiefiles",
  Anime: "simple-icons:anime",
  "Anime.js": "simple-icons:anime",
  Socket: "logos:socket-io",
  "Socket.io": "logos:socket-io",
  Axios: "simple-icons:axios",
  Lodash: "logos:lodash",
  Moment: "simple-icons:momentjs",
  "Moment.js": "simple-icons:momentjs",
  "date-fns": "simple-icons:datefns",
  Day: "simple-icons:dayjs",
  "Day.js": "simple-icons:dayjs",
  Zod: "simple-icons:zod",
  Yup: "simple-icons:yoga",
  RxJS: "logos:rxjs",
  Ramda: "logos:ramda",
  Immer: "simple-icons:immer",

  // Mobile Development
  "React Native": "logos:react",
  Flutter: "logos:flutter",
  Ionic: "logos:ionic-icon",
  Expo: "logos:expo-icon",
  Xamarin: "logos:xamarin",
  NativeScript: "logos:nativescript",
  Capacitor: "logos:capacitorjs-icon",
  Cordova: "logos:cordova",
  PWA: "logos:pwa",
  Tauri: "logos:tauri",
  Electron: "logos:electron",

  // CMS & E-commerce
  WordPress: "logos:wordpress-icon",
  Shopify: "logos:shopify",
  WooCommerce: "logos:woocommerce-icon",
  Magento: "logos:magento",
  Strapi: "logos:strapi-icon",
  Contentful: "logos:contentful",
  Sanity: "logos:sanity",
  Ghost: "logos:ghost",
  Drupal: "logos:drupal-icon",
  Joomla: "logos:joomla",
  Webflow: "logos:webflow",
  Wix: "logos:wix",
  Squarespace: "simple-icons:squarespace",
  Keystonejs: "simple-icons:keystonejs",
  KeystoneJS: "simple-icons:keystonejs",
  Directus: "simple-icons:directus",
  Payload: "simple-icons:payloadcms",
  "Payload CMS": "simple-icons:payloadcms",
  Medusa: "simple-icons:medusa",
  Saleor: "simple-icons:saleor",
  PrestaShop: "simple-icons:prestashop",
  BigCommerce: "simple-icons:bigcommerce",

  // Social Media & Communication
  Instagram: "logos:instagram-icon",
  Twitter: "logos:twitter",
  X: "simple-icons:x",
  LinkedIn: "logos:linkedin-icon",
  YouTube: "logos:youtube-icon",
  TikTok: "logos:tiktok-icon",
  Discord: "logos:discord-icon",
  WhatsApp: "logos:whatsapp-icon",
  Telegram: "logos:telegram",
  Facebook: "logos:facebook",
  Messenger: "logos:messenger",
  Slack: "logos:slack-icon",
  Zoom: "logos:zoom-icon",
  "Microsoft Teams": "logos:microsoft-teams",
  Teams: "logos:microsoft-teams",
  Skype: "logos:skype",
  Signal: "simple-icons:signal",
  Line: "simple-icons:line",
  WeChat: "simple-icons:wechat",
  Snapchat: "simple-icons:snapchat",
  Reddit: "logos:reddit-icon",
  Pinterest: "simple-icons:pinterest",
  Twitch: "logos:twitch",
  Clubhouse: "simple-icons:clubhouse",
  Threads: "simple-icons:threads",
  Mastodon: "logos:mastodon-icon",
  Bluesky: "simple-icons:bluesky",

  // Productivity & Project Management
  Notion: "logos:notion-icon",
  Trello: "logos:trello",
  Jira: "logos:jira",
  Asana: "logos:asana",
  Monday: "simple-icons:mondaydotcom",
  "Monday.com": "simple-icons:mondaydotcom",
  ClickUp: "simple-icons:clickup",
  Linear: "simple-icons:linear",
  Basecamp: "logos:basecamp-icon",
  Airtable: "logos:airtable",
  Coda: "simple-icons:coda",
  Obsidian: "simple-icons:obsidian",
  Roam: "simple-icons:roamresearch",
  "Roam Research": "simple-icons:roamresearch",
  Logseq: "simple-icons:logseq",
  Bear: "simple-icons:bear",
  "Apple Notes": "simple-icons:apple",
  Evernote: "simple-icons:evernote",
  OneNote: "simple-icons:microsoftonenote",
  "Microsoft OneNote": "simple-icons:microsoftonenote",
  Confluence: "logos:confluence",
  Todoist: "simple-icons:todoist",
  "Things 3": "simple-icons:things",
  TickTick: "simple-icons:ticktick",
  "Google Keep": "simple-icons:googlekeep",

  // Google Workspace
  Google: "logos:google-icon",
  "Google Drive": "logos:google-drive",
  "Google Docs": "simple-icons:googledocs",
  "Google Sheets": "simple-icons:googlesheets",
  "Google Slides": "simple-icons:googleslides",
  "Google Meet": "logos:google-meet",
  "Google Calendar": "logos:google-calendar",
  Gmail: "logos:google-gmail",
  "Google Forms": "simple-icons:googleforms",
  "Google Maps": "logos:google-maps",
  "Google Analytics": "logos:google-analytics",
  "Google Ads": "logos:google-ads",
  "Google Tag Manager": "logos:google-tag-manager",
  "Google Search Console": "simple-icons:googlesearchconsole",
  "Google Colab": "simple-icons:googlecolab",
  "Google Photos": "simple-icons:googlephotos",
  "Google Chat": "simple-icons:googlechat",
  "Google Play": "logos:google-play-icon",
  Chrome: "logos:chrome",
  "Google Chrome": "logos:chrome",

  // Microsoft Office & Apps
  Microsoft: "logos:microsoft-icon",
  "Microsoft Word": "vscode-icons:file-type-word",
  Word: "vscode-icons:file-type-word",
  "Microsoft Excel": "vscode-icons:file-type-excel",
  Excel: "vscode-icons:file-type-excel",
  "Microsoft PowerPoint": "vscode-icons:file-type-powerpoint",
  PowerPoint: "vscode-icons:file-type-powerpoint",
  "Microsoft Outlook": "vscode-icons:file-type-outlook",
  Outlook: "vscode-icons:file-type-outlook",
  "Microsoft Access": "vscode-icons:file-type-access",
  Access: "vscode-icons:file-type-access",
  "Microsoft Publisher": "logos:microsoft-icon",
  SharePoint: "devicon:sharepoint",
  "Microsoft SharePoint": "devicon:sharepoint",
  OneDrive: "logos:microsoft-onedrive",
  "Microsoft OneDrive": "logos:microsoft-onedrive",
  "Microsoft Edge": "logos:microsoft-edge",
  Edge: "logos:microsoft-edge",
  "Power BI": "logos:microsoft-power-bi",
  "Power Automate": "logos:microsoft-icon",
  "Power Apps": "logos:microsoft-icon",
  Copilot: "simple-icons:githubcopilot",
  "GitHub Copilot": "simple-icons:githubcopilot",
  "Microsoft Copilot": "simple-icons:microsoft",

  // Cloud Storage & File Sharing
  Dropbox: "logos:dropbox",
  Box: "simple-icons:box",
  iCloud: "simple-icons:icloud",
  "iCloud Drive": "simple-icons:icloud",
  MEGA: "simple-icons:mega",
  pCloud: "simple-icons:pcloud",
  Nextcloud: "logos:nextcloud-icon",
  Syncthing: "simple-icons:syncthing",

  // Companies & Tech Giants (unique entries only)
  Apple: "logos:apple",
  Amazon: "logos:aws",
  Meta: "logos:meta-icon",
  Netflix: "logos:netflix-icon",
  Spotify: "logos:spotify-icon",
  Airbnb: "logos:airbnb-icon",
  Uber: "logos:uber",
  Lyft: "simple-icons:lyft",
  Square: "simple-icons:square",
  Salesforce: "logos:salesforce",
  SAP: "logos:sap",
  IBM: "logos:ibm",
  Intel: "simple-icons:intel",
  AMD: "simple-icons:amd",
  NVIDIA: "logos:nvidia",
  Qualcomm: "simple-icons:qualcomm",
  Adobe: "logos:adobe",
  Autodesk: "simple-icons:autodesk",
  Atlassian: "logos:atlassian",
  Cisco: "logos:cisco",
  Dell: "simple-icons:dell",
  HP: "simple-icons:hp",
  Lenovo: "simple-icons:lenovo",
  Samsung: "simple-icons:samsung",
  Sony: "simple-icons:sony",
  LG: "simple-icons:lg",
  Xiaomi: "simple-icons:xiaomi",
  Huawei: "simple-icons:huawei",
  Tencent: "simple-icons:tencentqq",
  Alibaba: "simple-icons:alibabacloud",
  ByteDance: "simple-icons:bytedance",
  Baidu: "simple-icons:baidu",
  JD: "simple-icons:jd",
  Grab: "simple-icons:grab",
  Gojek: "simple-icons:gojek",
  Tokopedia: "simple-icons:tokopedia",
  Bukalapak: "simple-icons:bukalapak",
  Shopee: "simple-icons:shopee",
  Lazada: "simple-icons:lazada",
  Traveloka: "simple-icons:traveloka",

  // Payment & Finance (unique entries only)
  "Apple Pay": "logos:apple-pay",
  "Google Pay": "logos:google-pay",
  "Samsung Pay": "simple-icons:samsungpay",
  Venmo: "simple-icons:venmo",
  "Cash App": "simple-icons:cashapp",
  Wise: "simple-icons:wise",
  Revolut: "simple-icons:revolut",
  Klarna: "simple-icons:klarna",
  Afterpay: "simple-icons:afterpay",
  Affirm: "simple-icons:affirm",
  Plaid: "simple-icons:plaid",
  Braintree: "logos:braintree",
  Adyen: "simple-icons:adyen",
  Razorpay: "simple-icons:razorpay",
  Midtrans: "simple-icons:midtrans",
  GoPay: "simple-icons:gojek",
  OVO: "simple-icons:ovo",
  Dana: "simple-icons:dana",
  LinkAja: "simple-icons:linkaja",
  ShopeePay: "simple-icons:shopee",

  // Operating Systems
  Linux: "logos:linux-tux",
  Ubuntu: "logos:ubuntu",
  Debian: "logos:debian",
  Fedora: "logos:fedora",
  CentOS: "logos:centos-icon",
  "Red Hat": "logos:redhat-icon",
  RHEL: "logos:redhat-icon",
  "Arch Linux": "logos:archlinux",
  Arch: "logos:archlinux",
  Manjaro: "logos:manjaro",
  "Linux Mint": "logos:linux-mint",
  Mint: "logos:linux-mint",
  openSUSE: "logos:opensuse",
  Kali: "simple-icons:kalilinux",
  "Kali Linux": "simple-icons:kalilinux",
  "Alpine Linux": "simple-icons:alpinelinux",
  FreeBSD: "simple-icons:freebsd",
  Windows: "logos:microsoft-windows-icon",
  "Windows 10": "logos:microsoft-windows-icon",
  "Windows 11": "logos:microsoft-windows-icon",
  macOS: "logos:apple",
  Mac: "logos:apple",
  "Mac OS": "logos:apple",
  Android: "logos:android-icon",
  iOS: "logos:apple",
  iPadOS: "logos:apple",
  watchOS: "logos:apple",
  tvOS: "logos:apple",
  ChromeOS: "simple-icons:googlechrome",
  "Chrome OS": "simple-icons:googlechrome",
  HarmonyOS: "simple-icons:harmonyos",

  // AI & Machine Learning
  TensorFlow: "logos:tensorflow",
  PyTorch: "logos:pytorch-icon",
  Keras: "simple-icons:keras",
  "Scikit-learn": "simple-icons:scikitlearn",
  scikit: "simple-icons:scikitlearn",
  Pandas: "simple-icons:pandas",
  NumPy: "simple-icons:numpy",
  Jupyter: "logos:jupyter",
  "Jupyter Notebook": "logos:jupyter",
  OpenAI: "simple-icons:openai",
  ChatGPT: "simple-icons:openai",
  "GPT-4": "simple-icons:openai",
  Claude: "simple-icons:anthropic",
  Anthropic: "simple-icons:anthropic",
  Gemini: "simple-icons:googlegemini",
  "Google Gemini": "simple-icons:googlegemini",
  Bard: "simple-icons:google",
  Llama: "simple-icons:meta",
  "Hugging Face": "simple-icons:huggingface",
  HuggingFace: "simple-icons:huggingface",
  LangChain: "simple-icons:langchain",
  Ollama: "simple-icons:ollama",
  "Stable Diffusion": "simple-icons:stablediffusion",
  Midjourney: "simple-icons:midjourney",
  DALL: "simple-icons:openai",
  "DALL-E": "simple-icons:openai",
  Perplexity: "simple-icons:perplexity",
  Cohere: "simple-icons:cohere",
  "Vertex AI": "logos:google-cloud",
  SageMaker: "logos:aws-sagemaker",
  "AWS SageMaker": "logos:aws-sagemaker",
  "Azure ML": "logos:azure-icon",
  MLflow: "simple-icons:mlflow",
  Weights: "simple-icons:weightsandbiases",
  "Weights & Biases": "simple-icons:weightsandbiases",
  W: "simple-icons:weightsandbiases",
  "W&B": "simple-icons:weightsandbiases",
  CUDA: "simple-icons:nvidia",
  OpenCV: "logos:opencv",
  FastAI: "simple-icons:fastai",
  Spacy: "simple-icons:spacy",
  NLTK: "simple-icons:python",
  Matplotlib: "simple-icons:plotly",
  Plotly: "simple-icons:plotly",
  Seaborn: "simple-icons:python",
  Apache: "logos:apache",
  Spark: "simple-icons:apachespark",
  "Apache Spark": "simple-icons:apachespark",
  Hadoop: "logos:hadoop",
  "Apache Hadoop": "logos:hadoop",
  Airflow: "logos:airflow-icon",
  "Apache Airflow": "logos:airflow-icon",
  dbt: "simple-icons:dbt",
  Snowflake: "simple-icons:snowflake",
  Databricks: "simple-icons:databricks",
  BigQuery: "simple-icons:googlebigquery",
  "Google BigQuery": "simple-icons:googlebigquery",
  Redshift: "logos:aws-redshift",
  "AWS Redshift": "logos:aws-redshift",

  // Browsers
  Firefox: "logos:firefox",
  "Mozilla Firefox": "logos:firefox",
  Safari: "logos:safari",
  Opera: "logos:opera",
  Brave: "logos:brave",
  Arc: "simple-icons:arc",
  Vivaldi: "logos:vivaldi",
  Tor: "simple-icons:torbrowser",
  "Tor Browser": "simple-icons:torbrowser",

  // Infrastructure & DevOps Tools
  Nginx: "logos:nginx",
  Cloudflare: "logos:cloudflare-icon",
  RabbitMQ: "logos:rabbitmq-icon",
  Kafka: "logos:kafka-icon",
  "Apache Kafka": "logos:kafka-icon",
  Grafana: "logos:grafana",
  Prometheus: "logos:prometheus",
  Sentry: "logos:sentry-icon",
  Datadog: "logos:datadog",
  "New Relic": "logos:new-relic-icon",
  NewRelic: "logos:new-relic-icon",
  Splunk: "simple-icons:splunk",
  PagerDuty: "simple-icons:pagerduty",
  OpsGenie: "simple-icons:opsgenie",
  Consul: "logos:consul",
  Vault: "logos:vault-icon",
  "HashiCorp Vault": "logos:vault-icon",
  Nomad: "simple-icons:nomad",
  Packer: "logos:packer",
  Istio: "logos:istio",
  Envoy: "logos:envoy-icon",
  Kong: "logos:kong-icon",
  Traefik: "logos:traefik",
  HAProxy: "simple-icons:haproxy",
  Caddy: "simple-icons:caddy",
  Portainer: "simple-icons:portainer",
  Rancher: "logos:rancher-icon",
  OpenShift: "logos:openshift",
  Podman: "logos:podman",
  Containerd: "logos:containerd-icon",
  VirtualBox: "simple-icons:virtualbox",
  Proxmox: "simple-icons:proxmox",
  ESXi: "logos:vmware",
  "Amazon EC2": "logos:aws-ec2",
  EC2: "logos:aws-ec2",
  "Amazon S3": "logos:aws-s3",
  S3: "logos:aws-s3",
  Lambda: "logos:aws-lambda",
  "AWS Lambda": "logos:aws-lambda",
  ECS: "logos:aws-ecs",
  "AWS ECS": "logos:aws-ecs",
  EKS: "logos:aws-eks",
  "AWS EKS": "logos:aws-eks",
  CloudFront: "logos:aws-cloudfront",
  "AWS CloudFront": "logos:aws-cloudfront",
  Route53: "logos:aws-route53",
  "AWS Route 53": "logos:aws-route53",
  RDS: "logos:aws-rds",
  "AWS RDS": "logos:aws-rds",
  ElastiCache: "logos:aws-elasticache",
  "AWS ElastiCache": "logos:aws-elasticache",
  SNS: "logos:aws-sns",
  "AWS SNS": "logos:aws-sns",
  SQS: "logos:aws-sqs",
  "AWS SQS": "logos:aws-sqs",
  Kinesis: "logos:aws-kinesis",
  "AWS Kinesis": "logos:aws-kinesis",
  "API Gateway": "logos:aws-api-gateway",
  "AWS API Gateway": "logos:aws-api-gateway",
  Cognito: "logos:aws-cognito",
  "AWS Cognito": "logos:aws-cognito",
  IAM: "logos:aws-iam",
  "AWS IAM": "logos:aws-iam",
  CloudWatch: "logos:aws-cloudwatch",
  "AWS CloudWatch": "logos:aws-cloudwatch",
  CloudFormation: "logos:aws-cloudformation",
  "AWS CloudFormation": "logos:aws-cloudformation",
  CDK: "simple-icons:awsorganizations",
  "AWS CDK": "simple-icons:awsorganizations",
  Amplify: "logos:aws-amplify",
  "AWS Amplify": "logos:aws-amplify",
  AppSync: "logos:aws-appsync",
  "AWS AppSync": "logos:aws-appsync",
  Lightsail: "logos:aws-lightsail",
  "AWS Lightsail": "logos:aws-lightsail",
  Fargate: "logos:aws-fargate",
  "AWS Fargate": "logos:aws-fargate",
  Step: "logos:aws-step-functions",
  "Step Functions": "logos:aws-step-functions",
  "AWS Step Functions": "logos:aws-step-functions",
  EventBridge: "logos:aws-eventbridge",
  "AWS EventBridge": "logos:aws-eventbridge",
  "Elastic Beanstalk": "logos:aws-elastic-beanstalk",
  "AWS Elastic Beanstalk": "logos:aws-elastic-beanstalk",

  // Security
  Auth0: "logos:auth0-icon",
  Okta: "logos:okta-icon",
  Clerk: "simple-icons:clerk",
  NextAuth: "simple-icons:nextdotjs",
  "NextAuth.js": "simple-icons:nextdotjs",
  Keycloak: "simple-icons:keycloak",
  "Firebase Auth": "logos:firebase",
  JWT: "logos:jwt-icon",
  OAuth: "simple-icons:oauth",
  "Let's Encrypt": "simple-icons:letsencrypt",
  LetsEncrypt: "simple-icons:letsencrypt",
  SSL: "simple-icons:letsencrypt",
  TLS: "simple-icons:letsencrypt",
  HTTPS: "simple-icons:letsencrypt",
  Snyk: "simple-icons:snyk",
  SonarQube: "logos:sonarqube",
  "OWASP ZAP": "simple-icons:owasp",
  Burp: "simple-icons:burpsuite",
  "Burp Suite": "simple-icons:burpsuite",
  Nmap: "simple-icons:nmap",
  Wireshark: "simple-icons:wireshark",
  Metasploit: "simple-icons:metasploit",
  "1Password": "simple-icons:1password",
  LastPass: "simple-icons:lastpass",
  Bitwarden: "simple-icons:bitwarden",
  Dashlane: "simple-icons:dashlane",
  NordVPN: "simple-icons:nordvpn",
  ExpressVPN: "simple-icons:expressvpn",
  Surfshark: "simple-icons:surfshark",
  ProtonVPN: "simple-icons:protonvpn",
  ProtonMail: "simple-icons:protonmail",
  Proton: "simple-icons:proton",

  // Gaming & Entertainment
  Steam: "logos:steam-icon",
  Epic: "simple-icons:epicgames",
  "Epic Games": "simple-icons:epicgames",
  PlayStation: "simple-icons:playstation",
  Xbox: "simple-icons:xbox",
  Nintendo: "simple-icons:nintendoswitch",
  "Nintendo Switch": "simple-icons:nintendoswitch",
  Roblox: "simple-icons:roblox",
  Minecraft: "simple-icons:minecraft",
  "League of Legends": "simple-icons:leagueoflegends",
  "Genshin Impact": "simple-icons:genshinimpact",
  Valorant: "simple-icons:valorant",
  Fortnite: "simple-icons:epicgames",
  "Call of Duty": "simple-icons:activision",
  "EA Games": "simple-icons:ea",
  EA: "simple-icons:ea",
  Ubisoft: "simple-icons:ubisoft",
  Rockstar: "simple-icons:rockstargames",
  "Rockstar Games": "simple-icons:rockstargames",
  Blizzard: "simple-icons:blizzard",
  "Riot Games": "simple-icons:riotgames",
  Riot: "simple-icons:riotgames",
};

// Export available icon names for autocomplete
export const availableIcons = Object.keys(iconMap);

// Get icon identifier by name (for use in components)
export function getIconIdentifier(toolName: string): string | null {
  // Try exact match
  if (iconMap[toolName]) {
    return iconMap[toolName];
  }

  // Try case-insensitive match
  const lowerToolName = toolName.toLowerCase();
  const matchingKey = Object.keys(iconMap).find(
    (key) => key.toLowerCase() === lowerToolName
  );

  if (matchingKey) {
    return iconMap[matchingKey];
  }

  return null;
}

export function getToolIcon(toolName: string): React.ReactNode {
  const iconIdentifier = getIconIdentifier(toolName);

  if (iconIdentifier) {
    return <Icon icon={iconIdentifier} width="40" height="40" />;
  }

  // Fallback to generic code icon
  return <Icon icon="mdi:code-tags" width="40" height="40" />;
}
